Add new end point to get disk size information for search index
cloudant-labs/dreyfus pull request #17
Opened 2017-06-05 17:41 UTC by brkolla

Currently the only way to get the disk size information for the search
index is to use the _search_info end point. But using this point would
lead to opening the search index which is non trivial as lucene has an
overhead for opening the index.

These changes would add a new end point _search_disk_size to get the
disk size information without opening the search index. Sarnie can use
this new end point and avoid opening the search index.

BugzId:87336

2017-06-05 17:43 UTC, brkolla commented
@rnewson? Can you please review these changes?

2017-06-05 18:10 UTC, rnewson requested changes
remove the unnecessary case statement and this is good. thanks.

2017-06-05 18:10 UTC, rnewson commented on src/dreyfus_fabric_info.erl
> +            Workers = fabric_util:submit_jobs(Shards, dreyfus_rpc, info, [DDoc, IndexName]);
just pass InfoLevel here, you don't need the case statement.

2017-06-05 18:17 UTC, brkolla commented on src/dreyfus_fabric_info.erl
> +            Workers = fabric_util:submit_jobs(Shards, dreyfus_rpc, info, [DDoc, IndexName]);
That's what I started out with but I thought this would be more readable. Will switch it back

2017-06-06 08:03 UTC, rnewson approved these changes

2017-06-06 13:04 UTC, merged