[WIP]Move search index to .recovery directory when database is deleted
cloudant-labs/dreyfus pull request #19
Opened 2017-07-20 05:51 UTC by jiangphcn

Bugzid: 86318

2017-07-31 17:56 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +    case Msg of
make multiple clauses instead.

2017-07-31 17:56 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +    DoRecovery = config:get_boolean("couchdb",
`RecoveryEnabled` would be a better name, we're not 'doing' recovery here, we're just enabling a future recovery.

2017-08-01 03:13 UTC, jiangphcn commented
Thanks so much for your review, Bob. I addressed them and would you please take a look?

2017-08-01 17:48 UTC, rnewson commented
These changes look good but don't merge yet as this needs adjusting given the comments on the related clouseau PR.

2017-08-02 07:34 UTC, jiangphcn commented
Yes, need to align with the change of clouseau. I modified codes to move calculation of destination directory for recovering index to dreyfus/erlang part. Could you please take a look? Thanks

2017-08-02 10:00 UTC, rnewson requested changes

2017-08-02 10:00 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +handle_cast({move, DbName}, State) ->
This doesn't match the gen_server:cast above and so it doesn't work. When I review code I am assuming that you have run through a successful move, but that doesn't seem possible with this problem.

2017-08-02 10:00 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +            gen_server:cast(?MODULE, {move, DbName});
same problem here

2017-08-02 10:13 UTC, jiangphcn commented on src/dreyfus_index_manager.erl
> +handle_cast({move, DbName}, State) ->
Yes, I run a successful move before having this commit. It looks that `gen_server:cast(?MODULE, {move, DbName})` matches with `handle_cast({move, DbName}, State)`.

2017-08-02 10:29 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +            gen_server:cast(?MODULE, {move, DbName});
I'm also wrong here again, sorry.

2017-08-02 10:29 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +handle_cast({move, DbName}, State) ->
I see it, I read it backward.

2017-08-02 10:35 UTC, rnewson commented on src/dreyfus_index_manager.erl
> +    RecoveryDir = config:get("couchdb", "recovery_index_dir", ".recovery"),
the recovery dir should be specified as an absolute path. I think that needs to happen in the dbcore chef cookbook. It should be under the `[:clouseau][:index_dir]` directory.

2017-08-02 10:36 UTC, rnewson commented
the move Src Dest code looks fine to me. The next step is to figure out how we'll deploy the change. We need to get an absolute path from the config, so please make a chef-repo PR with that. Once that exists we can ensure all three PR's will work together before merging.

2017-08-03 13:09 UTC, jiangphcn commented
Okay, issued the third PR to make directories to be configurable:
https://github.com/cloudant/chef-repo/pull/7456

2017-08-04 12:01 UTC, rnewson commented
+1

2018-03-16 09:10 UTC, closed without merging