adjust metric for io_queue-search
cloudant-labs/dreyfus pull request #47
Opened 2019-05-10 02:49 UTC by jiangphcn

This PR is to eliminate `unknown metric: [couchdb,io_queue,search]` emission.

2019-05-13 18:43 UTC, chewbranca requested changes

2019-05-13 18:43 UTC, chewbranca commented on priv/stats_descriptions.cfg
> +
Good catch, I forgot to add the associated metric for IOQ1. This metric is updated by https://github.com/apache/couchdb-ioq/blob/master/src/ioq_server.erl#L424 and we can see it's of the format `[couchdb, io_queue, search]` and this change is correct.

2019-05-13 18:43 UTC, chewbranca commented on priv/stats_descriptions.cfg
> +{[couchdb, io_queue2, search], [
This is the corresponding search metric for IOQ2 and it should not have the format changed. You can see in https://github.com/apache/couchdb-ioq/blob/master/src/ioq_server2.erl#L451 that for IOQ2 class counters we're using the form `[couchdb, io_queue2, Class, count]`, so this change should be reverted unless you've specifically seen an issue with this. Your comment suggests that the unknown metric errors are _only_ for the IOQ1 case: `unknown metric: [couchdb,io_queue,search]`.

2019-05-14 01:07 UTC, jiangphcn commented
Thank you @chewbranca and @nickva. Good catch, the change on `[couchdb, io_queue2, search]` was reverted. Would you please approve this PR if there is no other comment?

2019-05-14 01:31 UTC, nickva approved these changes
@chewbranca thanks for taking a look. I had missed the part about ioq2 as well.

@jiangphcn nice, fix!

2019-05-14 01:37 UTC, merged